openapi: 3.0.3
info:
  title: Fuse 6 Status API - OpenAPI 3.0
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8182/cxf/status
tags:
  - name: status
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /custId/{id}:
    get:
      tags:
        - customer
      summary: Get customer status by ID
      operationId: getCustById
      parameters:
        - name: id
          in: path
          description: ID of customer
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
